#tomacat端口号
server:
  port: 8080
spring:
  #应用的名称，不必须
  application:
    name: reggie_take_out
    #配置数据源为druid
   #Redis配置
    #linux的redis的host不同password不同
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  cache:
    redis:
      time-to-live: 180000 #设置缓存过期时间

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #linux的ip修改
      url: jdbc:mysql://localhost/reggle?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      #linux的数据库密码修改
      password: root
   #设置文件上传时最大的单个文件大小，和最大的全部文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  #linux的图片路径
  basePath: D:\img1\




